"""NSE universes: Nifty 50, Nifty 100, and extended sector coverage."""

from __future__ import annotations

NIFTY_50_SYMBOLS: list[str] = [
    "ADANIENT",
    "ADANIPORTS",
    "APOLLOHOSP",
    "ASIANPAINT",
    "AXISBANK",
    "BAJAJ-AUTO",
    "BAJFINANCE",
    "BAJAJFINSV",
    "BPCL",
    "BHARTIARTL",
    "BRITANNIA",
    "CIPLA",
    "COALINDIA",
    "DIVISLAB",
    "DRREDDY",
    "EICHERMOT",
    "GRASIM",
    "HCLTECH",
    "HDFCBANK",
    "HDFCLIFE",
    "HEROMOTOCO",
    "HINDALCO",
    "HINDUNILVR",
    "ICICIBANK",
    "ITC",
    "INDUSINDBK",
    "INFY",
    "JSWSTEEL",
    "KOTAKBANK",
    "LT",
    "M&M",
    "MARUTI",
    "NTPC",
    "NESTLEIND",
    "ONGC",
    "POWERGRID",
    "RELIANCE",
    "SBILIFE",
    "SBIN",
    "SUNPHARMA",
    "TCS",
    "TATACONSUM",
    "TMPV",
    "TATASTEEL",
    "TECHM",
    "TITAN",
    "ULTRACEMCO",
    "WIPRO",
    "HDFCAMC",
]

NIFTY_100_EXTRA: list[str] = [
    "ABB",
    "ADANIGREEN",
    "AMBUJACEM",
    "AUROPHARMA",
    "BANKBARODA",
    "BEL",
    "BERGEPAINT",
    "BOSCHLTD",
    "CANBK",
    "CHOLAFIN",
    "COLPAL",
    "DABUR",
    "DLF",
    "GAIL",
    "GODREJCP",
    "HAVELLS",
    "ICICIPRULI",
    "INDIGO",
    "IOC",
    "JINDALSTEL",
    "LICI",
    "LTIM",
    "MOTHERSON",
    "NAUKRI",
    "PIDILITIND",
    "PNB",
    "SHREECEM",
    "SIEMENS",
    "TATAPOWER",
    "TORNTPHARM",
    "TRENT",
    "VEDL",
    "DMART",
    "HAL",
    "IRCTC",
    "JIOFIN",
    "MAXHEALTH",
    "NHPC",
    "POLYCAB",
    "SRF",
    "TVSMOTOR",
    "VBL",
    "YESBANK",
    "INDHOTEL",
    "PIIND",
    "MANKIND",
    "CGPOWER",
    "DIXON",
    "ETERNAL",
    "HUDCO",
    "IRFC",
    "RECLTD",
    "PFC",
    "UNIONBANK",
    "IDFCFIRSTB",
    "FEDERALBNK",
    "AUBANK",
    "MARICO",
    "PAGEIND",
    "PERSISTENT",
    "COFORGE",
    "MPHASIS",
    "OFSS",
    "TATAELXSI",
    "LUPIN",
    "BIOCON",
    "ALKEM",
    "ZYDUSLIFE",
    "ICICIGI",
    "MUTHOOTFIN",
    "SHRIRAMFIN",
    "GODREJPROP",
    "OBEROIRLTY",
    "PHOENIXLTD",
    "PRESTIGE",
    "BHEL",
    "CONCOR",
    "SAIL",
    "NMDC",
    "NATIONALUM",
    "HINDZINC",
    "OIL",
    "PETRONET",
    "IGL",
    "MGL",
]

NIFTY_100_SYMBOLS: list[str] = sorted(set(NIFTY_50_SYMBOLS + NIFTY_100_EXTRA))

# All sectors represented (used for reports)
ALL_SECTORS: list[str] = [
    "Banking",
    "IT",
    "Energy",
    "Metal",
    "Pharma",
    "Finance",
    "Auto",
    "FMCG",
    "Infra",
    "Telecom",
    "Realty",
    "Aviation",
    "Chemicals",
    "Consumer",
    "Healthcare",
    "PSU",
    "Services",
]


def get_scan_universe() -> list[str]:
    """Full liquid universe for sector scan + intraday (Nifty 100)."""
    return list(NIFTY_100_SYMBOLS)


def to_yfinance_symbol(symbol: str) -> str:
    from config import YFINANCE_SUFFIX

    return f"{symbol}{YFINANCE_SUFFIX}"
