"""Nifty 50 / Nifty 100 universe (NSE tickers without suffix)."""

NIFTY_50_SYMBOLS: list[str] = [
    "ADANIENT",
    "ADANIPORTS",
    "APOLLOHOSP",
    "ASIANPAINT",
    "AXISBANK",
    "BAJAJ-AUTO",
    "BAJFINANCE",
    "BAJAJFINSV",
    "BPCL",
    "BHARTIARTL",
    "BRITANNIA",
    "CIPLA",
    "COALINDIA",
    "DIVISLAB",
    "DRREDDY",
    "EICHERMOT",
    "GRASIM",
    "HCLTECH",
    "HDFCBANK",
    "HDFCLIFE",
    "HEROMOTOCO",
    "HINDALCO",
    "HINDUNILVR",
    "ICICIBANK",
    "ITC",
    "INDUSINDBK",
    "INFY",
    "JSWSTEEL",
    "KOTAKBANK",
    "LT",
    "M&M",
    "MARUTI",
    "NTPC",
    "NESTLEIND",
    "ONGC",
    "POWERGRID",
    "RELIANCE",
    "SBILIFE",
    "SBIN",
    "SUNPHARMA",
    "TCS",
    "TATACONSUM",
    "TATAMOTORS",
    "TATASTEEL",
    "TECHM",
    "TITAN",
    "ULTRACEMCO",
    "WIPRO",
    "HDFCAMC",
]

# Additional liquid large-caps (Nifty Next 50 style universe)
NIFTY_100_EXTRA: list[str] = [
    "ABB",
    "ADANIGREEN",
    "AMBUJACEM",
    "AUROPHARMA",
    "BANKBARODA",
    "BEL",
    "BERGEPAINT",
    "BOSCHLTD",
    "CANBK",
    "CHOLAFIN",
    "COLPAL",
    "DABUR",
    "DLF",
    "GAIL",
    "GODREJCP",
    "HAVELLS",
    "HDFCAMC",
    "ICICIPRULI",
    "INDIGO",
    "IOC",
    "JINDALSTEL",
    "LICI",
    "LTIM",
    "MOTHERSON",
    "NAUKRI",
    "PIDILITIND",
    "PNB",
    "SHREECEM",
    "SIEMENS",
    "TATAPOWER",
    "TORNTPHARM",
    "TRENT",
    "VEDL",
    "ZOMATO",
    "DMART",
    "HAL",
    "IRCTC",
    "JIOFIN",
    "MAXHEALTH",
    "NHPC",
    "NYKAA",
    "PAYTM",
    "POLYCAB",
    "SRF",
    "TVSMOTOR",
    "VBL",
    "YESBANK",
    "INDHOTEL",
    "PIIND",
    "MANKIND",
]

NIFTY_100_SYMBOLS: list[str] = sorted(set(NIFTY_50_SYMBOLS + NIFTY_100_EXTRA))


def to_yfinance_symbol(symbol: str) -> str:
    from config import YFINANCE_SUFFIX

    return f"{symbol}{YFINANCE_SUFFIX}"
